# Generated by Django 3.0.4 on 2021-09-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('course', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
